### ISSUE TITLE
Bug affichage menu

### ISSUE THREAD

**Issue by ArnaudRegnier** [swimaf/empli-tude#6]
Quand on est sur le menu et qu'on était précédament dans Emploi du temps/reveil/todolist/gestion des sons et que l'on se rend dans a propos/parametres l'ancien quandon réouvre le mennu l'ancienne onglet reste grisé, par exemple on est sur paramètres et il y affiche que l'onglet actif est révéil.

**Comment by swimaf** [comment]
Ta la dernière version ?

**Comment by ArnaudRegnier** [comment]
Non, mais il me semblait avoir vue le bug sur la 2.9 je te dit ça après

**Comment by swimaf** [comment]
Normalement c'est corrigé dans la 2.10 grace aux activités

**Comment by ArnaudRegnier** [comment]
Le problème est effectivement corrigé avec le retour arrière.
